### ISSUE TITLE
ImportError: No module named docutils.core

### ISSUE THREAD

**Issue by ozesno** [marianoguerra/rst2html5#14]
Getting it:

warlo@default:~/Documents$ git clone https://github.com/marianoguerra/rst2html5.git
Cloning into 'rst2html5'...
remote: Counting objects: 316, done.
remote: Compressing objects: 100% (214/214), done.
remote: Total 316 (delta 121), reused 285 (delta 90)
Receiving objects: 100% (316/316), 1.22 MiB | 442 KiB/s, done.
Resolving deltas: 100% (121/121), done.

Following install instruction #1:
warlo@default:~/Documents$ cd rst2html5

Following install instruction #2:
warlo@default:~/Documents/rst2html5$ git submodule update --init
Submodule 'thirdparty/deckjs' (https://github.com/imakewebthings/deck.js) registered for path 'thirdparty/deckjs'
Submodule 'thirdparty/revealjs' (https://github.com/hakimel/reveal.js.git) registered for path 'thirdparty/revealjs'
Cloning into 'thirdparty/deckjs'...
remote: Counting objects: 1674, done.
remote: Compressing objects: 100% (648/648), done.
remote: Total 1674 (delta 1053), reused 1605 (delta 1012)
Receiving objects: 100% (1674/1674), 534.64 KiB | 223 KiB/s, done.
Resolving deltas: 100% (1053/1053), done.
Submodule path 'thirdparty/deckjs': checked out 'e1ba017e0e2bb075edeb0f7b9681cad80e7a19e7'
Cloning into 'thirdparty/revealjs'...
remote: Counting objects: 1952, done.
remote: Compressing objects: 100% (887/887), done.
remote: Total 1952 (delta 1070), reused 1817 (delta 975)
Receiving objects: 100% (1952/1952), 734.89 KiB | 316 KiB/s, done.
Resolving deltas: 100% (1070/1070), done.
Submodule path 'thirdparty/revealjs': checked out '143fc85c657a4953d3f3b878b845cc60efbed748'

Running it:
warlo@default:~/Documents/rst2html5$ bin/rst2html5 --jquery --reveal-js --pretty-print-code examples/pres.rst > reveal.html
Traceback (most recent call last):
  File "bin/rst2html5", line 20, in <module>
    from docutils.core import publish_cmdline, default_description
ImportError: No module named docutils.core

I tried with the 3 commands suggested (reveal, deck and bootstrap) with no luck, I also tried running it over the example slides.rst, still no go.

**Comment by mikenk2010** [comment]
or you can try `pip install docutils`
