### ISSUE TITLE
RST elements header and footer

### ISSUE THREAD

**Issue by russkel** [marianoguerra/rst2html5#31]
The RST elements header and footer are for placing markup at the, believe it or not, header and footer of the site. There is no real specifics on the implementation on this. I guess it could just be a `div.header` after the docinfo table and `div.footer` at the end of the page.

Pull request #30 handles the HTML5 `header` element. Seeing as there is no way to define a section footer in RST, the HTML5 `footer` element isn't required.

**Comment by G1305** [comment]
![image](https://user-images.githubusercontent.com/34474564/34104090-920c9c1c-e408-11e7-9710-6e11ad02c6e8.png)
I want full HEIGHT/width responsive for mobile. HOW TO FIX IT?
