### ISSUE TITLE
raw html is escaped

### ISSUE THREAD

**Issue by gdw2** [marianoguerra/rst2html5#46]
If the follwing is found in a to-be-translated rst document:

```
.. raw:: html

   Hello <b> World</b>
```

It is translated to this:
```Hello &lt;b&gt; World&lt;/b&gt;```

It should not escape the html, but instead should work like the vanilla `rst2html` and leave the tags in tact.

**Comment by torfsen** [comment]
I think this has been fixed in PR #74.
