### ISSUE TITLE
Add test framework

### ISSUE THREAD

**Issue by torfsen** [marianoguerra/rst2html5#75]
While I was working on my fix for #72, I would have loved to write some test to make sure that my fix does indeed solve all the problems. However, `rst2html5` currently doesn't seem to have any tests at all, and since I was not sure how to proceed I decided to raise this as a separate issue.

Since `rst2html5` supports multiple versions of Python I suggest using [tox](https://tox.readthedocs.org/en/latest/). Since `tox` itself only automates running the tests for the target Python versions one still needs a test framework for the tests itself. I suggest [pytest](http://pytest.org/latest/).

If this sounds OK to you I'd be happy to set it up and provide a PR.

**Comment by marianoguerra** [comment]
:+1:
