### ISSUE TITLE
IOError: ... deck.hash.css with --deck-js  option

### ISSUE THREAD

**Issue by LuisBL** [marianoguerra/rst2html5#81]
Hello the extensions/hash seems to be missing.

IOError: ... deck.hash.css with --deck-js  option    

    $ git log --pretty=oneline | head -1
    0950ae53319496e67e2235f1096b31ac28edbb3e (HEAD -> master, origin/master, origin/HEAD) Merge pull request #80 from torfsen/fix79

    $ rst2html5 --deck-js --pretty-print-code --embed-content examples/slides.rst > deck.html
    IOError: [Errno 2] No such file or directory: '/home/luis/lab/local/lib/python2.7/site-packages/rst2html5_tools-0.4.0-py2.7.egg/html5css3/thirdparty/deckjs/extensions/hash/deck.hash.css'
    Exiting due to error.  Use "--traceback" to diagnose.
    Please report errors to <docutils-users@lists.sf.net>.
    Include "--traceback" output, Docutils version (0.12 [release]),
    Python version (2.7.10), your OS type & version, and the
    command line used.
    $

**Comment by nabilbendafi** [comment]
I faced similar situation for RevealJS. I've pulled a request about it https://github.com/marianoguerra/rst2html5/pull/83.
Problem should be similar to yours, while sub-module projects (ImpressJS, RevealJS and DeckJS) might be out of sync.
If that can help.

**Comment by marianoguerra** [comment]
should be fixed now, check and tell me if I can close this issue

thanks for reporting!

btw, there's a new version with all this fixes and your PR :)

https://pypi.python.org/pypi/rst2html5-tools/0.5.0

**Comment by nabilbendafi** [comment]
Tested OK in version 0.5.0.
Generation done. Ready to close.

**Comment by marianoguerra** [comment]
@nabilbendafi thanks!
