### ISSUE TITLE
Regression with Reveal.js 

### ISSUE THREAD

**Issue by nabilbendafi** [marianoguerra/rst2html5#88]
Hi.
Is there any good reason why your last commit @7e315abea5e724bfd57130f2e1d48151f3ff139e is pointing  toward an old version of Reveal.js hakimel/reveal.js@9da952fea30906090446d038430186b11dba7f13  (25 Mar 2014) ?
I'm wondering because I got some error about a missing file when I try to build using Reveal.js
```
html5css3/thirdparty/revealjs/css/theme/league.css
```

It was working fine previously @6c2d092687ecd6599938f9e210e62c0799851397

**Comment by marianoguerra** [comment]
closing since PR was merged.

did you reverted the change or pulled a newer version of revealjs?

**Comment by nabilbendafi** [comment]
Just reverted changes.
