### ISSUE TITLE
full-screen image slide

### ISSUE THREAD

**Issue by comotion** [marianoguerra/rst2html5#89]
Hello,
I can't find any documentation on how to generate a full screen image slide, such that there is no title and only the image is shown.

Is there any way to set an image, and only that image, to be the slide contents?

ie:
```
my title
======

* bah
* foo

.. nextslide::

.. image:: zool.jpg
  :class: fill
```

This doesn't work, because I can't find any nextslide directive.

**Comment by marianoguerra** [comment]
you can hide the title like in examples/slide1.rst

    .. class:: hide-title

    .
    =

add a class .hide-title { display: none } and .fill { [full sreen css here] }
